name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
      - name: run tests
        run: chmod +x gradlew && ./gradlew --tests "sku.processsor.generator.request.app.E2ETest" --no-daemon
